[theme]
theme = "slick"
[icons]
icons = "awesome4"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon frequency{ $boost|} "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "load"
# format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 60
[block.format]
# full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "

#[[block]]
#block = "battery"
#interval = 10
#format = "{percentage} {time}"

#[[block]]
#block = "backlight"
#minimum = 15
#maximum = 100
#cycle = [100, 90, 80, 73, 55, 37, 23, 17]
