#!/usr/bin/env bash
echo "Download the repos..."
#git clone https://github.com/elsuizo/Dots_files.git
git clone https://github.com/elsuizo/Control1.git
git clone https://github.com/elsuizo/TODO_list.git
git clone https://github.com/elsuizo/Poles_adventures.git
git clone https://github.com/elsuizo/Objects_detection.git
git clone https://github.com/elsuizo/opencv.git
git clone https://github.com/elsuizo/C_work.git
git clone https://github.com/elsuizo/AVR_programming.git
git clone https://github.com/elsuizo/Haskell_work.git
git clone https://github.com/elsuizo/CodeJam.git
git clone https://github.com/elsuizo/Julia_work.git
git clone https://github.com/elsuizo/Robotics.git
git clone https://github.com/elsuizo/Cheatsheets.git
git clone https://github.com/elsuizo/Sistemas_digitales_TPF.git
git clone https://github.com/elsuizo/Sistemas_digitales.git
git clone https://github.com/elsuizo/Kivy_work.git
git clone https://github.com/elsuizo/Rust_work.git
git clone https://github.com/elsuizo/Cpp.git
git clone https://github.com/elsuizo/Telecomunicaciones.git
git clone https://github.com/elsuizo/Rosette.git
git clone https://github.com/elsuizo/Euler.git
git clone https://github.com/elsuizo/Numerical_methods.git
git clone https://github.com/elsuizo/Image_processing.git
git clone https://github.com/elsuizo/SFML_work.git
git clone https://github.com/elsuizo/Cpp_real_time.git
git clone https://github.com/elsuizo/Nonlinear_systems.git
git clone https://github.com/elsuizo/Python_work_git.git
git clone https://github.com/elsuizo/Practicas_vision.git
git clone https://github.com/elsuizo/elsuizo.github.io.git
git clone https://github.com/elsuizo/Optical_flow.git
git clone https://github.com/elsuizo/Charlas_presentaciones.git
git clone ttps://github.com/elsuizo/Control_de_robots_py.git
git clone https://github.com/elsuizo/pysimiam.git
git clone https://github.com/elsuizo/Redes_fuzzy.git
git clone https://github.com/elsuizo/Fortran_work.git
git clone https://github.com/elsuizo/K-vector.git
git clone https://github.com/elsuizo/Beaglebone_opencv.git
