theme = "slick"
icons = "awesome"

[[block]]
block = "pomodoro"
length = 37
break_length = 7
message = "Take a break!"
break_message = "Back to work!"
notifier = "i3nag"

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid} {signal_strength}"
interval = 5

[[block]]
block = "disk_space"
path = "/home"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "backlight"
minimum = 15
maximum = 100
cycle = [100, 90, 80, 73, 55, 37, 23, 17]
