[theme]
theme = "slick"
[theme.overrides]
idle_bg = "#F2EEDE"
idle_fg = "#000000"
good_fg = { link = "idle_bg" }
good_bg = { link = "idle_fg" }
info_bg = { link = "idle_bg" }
info_fg = { link = "idle_fg" }

[icons]
icons = "material-nf"

[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false

[[block]]
block = "net"
device = "enp4s0"
# format = "{ssid} {signal_strength}"
interval = 5

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "load"
# format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%m-%d %R') "
# short = " $icon $timestamp.datetime(f:%R) "

#[[block]]
#block = "battery"
#interval = 10
#format = "{percentage} {time}"

#[[block]]
#block = "backlight"
#minimum = 15
#maximum = 100
#cycle = [100, 90, 80, 73, 55, 37, 23, 17]
