[theme]
theme = "slick"
[icons]
icons = "awesome4"

[[block]]
block = "pomodoro"
notify_cmd = "i3nag"
blocking_cmd = true
# notifier = "i3nag"

[[block]]
block = "net"
device = "wlan0"
format = " $icon {$signal_strength $ssid}"
interval = 5

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "load"
# format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 60
[block.format]
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "battery"
format = "$icon $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "backlight"
minimum = 15
maximum = 100
cycle = [100, 90, 80, 73, 55, 37, 23, 17]
