#!/usr/bin/env bash
yes | sudo pacman -S otf-aurulent-nerd
yes | sudo pacman -S otf-cascadia-code-nerd
yes | sudo pacman -S otf-codenewroman-nerd
yes | sudo pacman -S otf-comicshanns-nerd
yes | sudo pacman -S otf-droid-nerd
yes | sudo pacman -S otf-firamono-nerd
yes | sudo pacman -S otf-hasklig-nerd
yes | sudo pacman -S otf-hermit-nerd
yes | sudo pacman -S otf-opendyslexic-nerd
yes | sudo pacman -S otf-overpass-nerd
yes | sudo pacman -S ttf-3270-nerd
yes | sudo pacman -S ttf-agave-nerd
yes | sudo pacman -S ttf-anonymouspro-nerd
yes | sudo pacman -S ttf-arimo-nerd
yes | sudo pacman -S ttf-bigblueterminal-nerd
yes | sudo pacman -S ttf-bitstream-vera-mono-nerd
yes | sudo pacman -S ttf-cascadia-code-nerd
yes | sudo pacman -S ttf-cousine-nerd
yes | sudo pacman -S ttf-daddytime-mono-nerd
yes | sudo pacman -S ttf-dejavu-nerd
yes | sudo pacman -S ttf-fantasque-nerd
yes | sudo pacman -S ttf-firacode-nerd
yes | sudo pacman -S ttf-go-nerd
yes | sudo pacman -S ttf-hack-nerd
yes | sudo pacman -S ttf-heavydata-nerd
yes | sudo pacman -S ttf-iawriter-nerd
yes | sudo pacman -S ttf-ibmplex-mono-nerd
yes | sudo pacman -S ttf-inconsolata-go-nerd
yes | sudo pacman -S ttf-inconsolata-lgc-nerd
yes | sudo pacman -S ttf-inconsolata-nerd
yes | sudo pacman -S ttf-iosevka-nerd
yes | sudo pacman -S ttf-iosevkaterm-nerd
yes | sudo pacman -S ttf-jetbrains-mono-nerd
yes | sudo pacman -S ttf-lekton-nerd
yes | sudo pacman -S ttf-liberation-mono-nerd
yes | sudo pacman -S ttf-lilex-nerd
yes | sudo pacman -S ttf-meslo-nerd
yes | sudo pacman -S ttf-monofur-nerd
yes | sudo pacman -S ttf-monoid-nerd
yes | sudo pacman -S ttf-mononoki-nerd
yes | sudo pacman -S ttf-mplus-nerd
yes | sudo pacman -S ttf-nerd-fonts-symbols
yes | sudo pacman -S ttf-nerd-fonts-symbols-common
yes | sudo pacman -S ttf-nerd-fonts-symbols-mono
yes | sudo pacman -S ttf-noto-nerd
yes | sudo pacman -S ttf-profont-nerd
yes | sudo pacman -S ttf-proggyclean-nerd
yes | sudo pacman -S ttf-roboto-mono-nerd
yes | sudo pacman -S ttf-sharetech-mono-nerd
yes | sudo pacman -S ttf-sourcecodepro-nerd
yes | sudo pacman -S ttf-space-mono-nerd
yes | sudo pacman -S ttf-terminus-nerd
yes | sudo pacman -S ttf-tinos-nerd
yes | sudo pacman -S ttf-ubuntu-mono-nerd
yes | sudo pacman -S ttf-ubuntu-nerd
yes | sudo pacman -S ttf-victor-mono-nerd
